# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amqp-artemis
  name: amqp-artemis
spec:
  ports:
  - name: "5672"
    nodePort: 30974
    port: 5672
    targetPort: 5672
  - name: "8161"
    nodePort: 32014
    port: 8161
    targetPort: 8161
  - name: "61616"
    nodePort: 30486
    port: 61616
    targetPort: 61616
  selector:
    app: amqp-artemis-pod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amqp-artemis
  name: amqp-artemis-deployment
spec:
  selector:
    matchLabels:
      app: amqp-artemis-pod
  template:
    metadata:
      labels:
        app: amqp-artemis-pod
      name: amqp-artemis-pod
    spec:
      containers:
      - env:
        - name: AMQ_USER
          value: quarkus
        - name: AMQ_PASSWORD
          value: quarkus
        - name: AMQ_EXTRA_ARGS
          value: --relax-jolokia
        image: quay.io/artemiscloud/activemq-artemis-broker:latest
        name: amqp-artemis-pod-amqp-artemis
        ports:
        - containerPort: 5672
        - containerPort: 8161
        - containerPort: 61616
        securityContext:
          runAsNonRoot: true
      restartPolicy: Always