# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: amqp-artemis-pod
  name: amqp-artemis-pod
spec:
  containers:
  - env:
    - name: AMQ_PASSWORD
      value: quarkus
    - name: AMQ_USER
      value: quarkus
    - name: AMQ_EXTRA_ARGS
      value: "--relax-jolokia"
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    name: amqp-artemis
    ports:
    - containerPort: 5672
      hostPort: 5672
    - containerPort: 8161
      hostPort: 8161
    - containerPort: 61616
      hostPort: 61616
    securityContext:
      runAsNonRoot: true