apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-broker
  namespace: amq-broker
spec:
  acceptors:
  - connectionsAllowed: 5
    name: acceptor-std
    port: 5672
    protocols: amqp,core
  adminPassword: redhat1!
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    jolokiaAgentEnabled: true
    journalType: nio
    managementRBACEnabled: true
    messageMigration: true
    persistenceEnabled: true
    requireLogin: false
    size: 2
